BLACK: int
RED: int
GREEN: int
BLUE: int
WHITE: int

def init() -> None: ...
def clear(color: int) -> None: ...
def rect(x: int, y: int, w: int, h: int, color: int) -> None: ...
def tile(x: int, y: int, color: int, top_color: int) -> None: ...
def load_tile_sprite(tile_id: int, data: bytes) -> None: ...
def tile_sprite(x: int, y: int, tile_id: int) -> None: ...
def load_player_sprite(data: bytes) -> None: ...
def player(x: int, y: int, flip_x: bool = False) -> None: ...
def present() -> None: ...
def btn_left() -> bool: ...
def btn_right() -> bool: ...
def btn_jump() -> bool: ...
def action_x() -> int: ...
def action_y() -> int: ...
def action_dig() -> bool: ...
def action_place() -> bool: ...
def ticks_ms() -> int: ...
def sleep_ms(ms: int) -> None: ...
def frame_ms() -> int: ...
def fps() -> int: ...
def spi_baudrate() -> int: ...
